### ISSUE TITLE
queryGlobalRegistry() throwing "TypeError: g is undefined" even after removing uglify step

### ISSUE THREAD

**Issue by ishantiw** [reTHINK-project/dev-runtime-browser#51]
I'm getting error while running [`queryGlobalRegistry(guid)`](https://github.com/reTHINK-project/dev-runtime-browser/blob/develop-GraphConnector-Test/example/guid.js#L87). As suggested in issue #48, I removed uglify step but still it's not working and throwing the following error.

![image](https://cloud.githubusercontent.com/assets/9600691/15898425/929a0b10-2d98-11e6-9390-6fc9094cac28.png)

Looks like the error is coming from the KJUR library but the tests are running successfully in runtime_core. Can anyone please help me to find what can be the reason of getting this error ?

**Comment by ishan210788** [comment]
I'm using Mozilla Firefox and now I'm getting a bit different error(but still its 'g is undefined" error) and this time I commented other functions like below in order to get proper logs. @dvilchez Can you please try to test like this to get the exact error from this function. 
![image](https://cloud.githubusercontent.com/assets/9600691/15926787/13a6e624-2e3e-11e6-81b4-b3a9a5b01e26.png)

 I got this error for queryGlobalRegistry(guid) function 
![image](https://cloud.githubusercontent.com/assets/9600691/15926640/7b5cf9f8-2e3d-11e6-9a80-5fb3e119b460.png)
Below are the corresponding logs on message_vrtx. 
![image](https://cloud.githubusercontent.com/assets/9600691/15926680/b7ba8ac8-2e3d-11e6-82ee-fde662e8cb73.png)

**Comment by dvilchez** [comment]
@ishan210788 : I can't reproduce your error with the code pushed right now

I got this:
![screen-shot-2016-06-09-12-45-24](https://cloud.githubusercontent.com/assets/153025/15927160/1ede31bc-2e40-11e6-8608-e60c4b7ddd5a.png)
![screen-shot-2016-06-09-12-45-00](https://cloud.githubusercontent.com/assets/153025/15927161/1ee16c74-2e40-11e6-8040-0773022ef4b6.png)

**Comment by ishantiw** [comment]
Hello @dvilchez Now I'm getting the same error as you are getting on my chrome browser and on msg_vrtx.
![image](https://cloud.githubusercontent.com/assets/9600691/16048055/e3253c8a-3252-11e6-8d79-d90d1fab7ad7.png)
I think the "TypeError" is coming because there is no record for the given GUID. But can you please tell why we are getting "Failed to execute atob on window" error.

**Comment by dvilchez** [comment]
@ishantiw please refers to this issue https://github.com/reTHINK-project/dev-hyperty/issues/32

**Comment by ishantiw** [comment]
@dvilchez I don't have access to this repository
